// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZwmAHmEBNZL0Ld-jrRJDeUFwij8iaMXU',
    appId: '1:571845170033:web:cda7e5227af930faa45cd0',
    messagingSenderId: '571845170033',
    projectId: 'aast-restaurant',
    authDomain: 'aast-restaurant.firebaseapp.com',
    storageBucket: 'aast-restaurant.appspot.com',
    measurementId: 'G-XSLJ0HCJ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4BK4ysoF-enH2cNyAgEnP2GB3aLhXTU',
    appId: '1:571845170033:android:979eef6996f42bf2a45cd0',
    messagingSenderId: '571845170033',
    projectId: 'aast-restaurant',
    storageBucket: 'aast-restaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QrNvuJPh5oy2S5-mzyvMpGx_be6pUTY',
    appId: '1:571845170033:ios:320018b47943d393a45cd0',
    messagingSenderId: '571845170033',
    projectId: 'aast-restaurant',
    storageBucket: 'aast-restaurant.appspot.com',
    iosBundleId: 'com.example.aastRestuarant',
  );
}
